name: sistem_pelaporan
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  animated_notch_bottom_bar: ^0.0.6
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_core: ^2.11.0
  firebase_storage: ^11.2.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  flutter_map_directions: ^0.0.3
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  http: ^0.13.2
  image_picker: ^0.8.7+5
  dropdown_textfield: ^1.0.8
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  video_player: ^2.7.0
  shared_preferences: ^2.2.1
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  awesome_dialog: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
