// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTJanY5nxFd5fgnnJNFxnVqLpRwFE5OU8',
    appId: '1:988093995191:web:5323a4be003eedaf0c9532',
    messagingSenderId: '988093995191',
    projectId: 'sistem-pelaporan-8e835',
    authDomain: 'sistem-pelaporan-8e835.firebaseapp.com',
    storageBucket: 'sistem-pelaporan-8e835.appspot.com',
    measurementId: 'G-CB567EKBCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnAfElBt_3xVHMvWW9gyFndQduH2ijPUA',
    appId: '1:988093995191:android:157850d98ed238dc0c9532',
    messagingSenderId: '988093995191',
    projectId: 'sistem-pelaporan-8e835',
    storageBucket: 'sistem-pelaporan-8e835.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMyY3ORGKa-zTQPKBBc1hZj711egG1-0w',
    appId: '1:988093995191:ios:1bd0e683b52676790c9532',
    messagingSenderId: '988093995191',
    projectId: 'sistem-pelaporan-8e835',
    storageBucket: 'sistem-pelaporan-8e835.appspot.com',
    iosClientId: '988093995191-t2d02kpirfavq1hcgerdnsttmi5cfdu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemPelaporan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMyY3ORGKa-zTQPKBBc1hZj711egG1-0w',
    appId: '1:988093995191:ios:68430cc66d9420fb0c9532',
    messagingSenderId: '988093995191',
    projectId: 'sistem-pelaporan-8e835',
    storageBucket: 'sistem-pelaporan-8e835.appspot.com',
    iosClientId: '988093995191-7je4g12daekvjde1khodcvlrb9atfktg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemPelaporan.RunnerTests',
  );
}
